# Generated by Django 4.1.1 on 2022-10-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classify", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=4)),
            ],
        ),
    ]
