# Generated by Django 4.0.2 on 2022-10-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='course_number',
            field=models.IntegerField(default=0),
        ),
    ]
