# Generated by Django 4.0.2 on 2022-11-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0006_all_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='meetings_end_time',
            field=models.SlugField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='class',
            name='meetings_start_time',
            field=models.SlugField(default='', max_length=10),
        ),
    ]
