# Generated by Django 4.0.2 on 2022-11-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0007_class_meetings_end_time_class_meetings_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='name',
        ),
        migrations.AddField(
            model_name='class',
            name='component',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='class',
            name='course_section',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='class',
            name='enrollment_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='facility_description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='class',
            name='instructor_email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='class',
            name='semester_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='topic',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='catalog_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='class',
            name='instructor_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='meetings_days',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='class',
            name='units',
            field=models.CharField(default='', max_length=2),
        ),
    ]
