# Generated by Django 4.0.2 on 2022-11-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0008_remove_class_name_class_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='units',
            field=models.CharField(default='', max_length=10),
        ),
    ]
