# Generated by Django 4.0.2 on 2022-11-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0009_alter_class_subject_alter_class_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='classify.Class')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classify.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='All_class',
        ),
    ]
