# Generated by Django 4.0.2 on 2022-11-02 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0010_schedule_delete_all_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.profile'),
        ),
    ]
