# Generated by Django 4.0.2 on 2022-11-04 21:48

from django.db import migrations, models
#import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0012_alter_schedule_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('address', django_google_maps.fields.AddressField(max_length=200)),
                #('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
    ]
