# Generated by Django 4.0.2 on 2022-11-06 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0013_facility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
